### ISSUE TITLE
Add @summary to default templates

### ISSUE THREAD

**Issue by vdininski** [jsdoc2md/dmd#13]
Not 100% sure, but I think that the `@summary` jsdoc tag is not added in the default markdown templates. If this is the case I could make a make a pull request later today (for the `next` branch) with support for it.

**Comment by 75lb** [comment]
true, i haven't added that tag yet.. if you already added then yes, throw over the PR - thanks for the input :+1: 

i'm a couple of planned improvements away from a release candidate - not too long now, i hope..

**Comment by 75lb** [comment]
`@summary` support is in dmd@next now

**Comment by 75lb** [comment]
this is in the latest version, [example here](https://github.com/jsdoc2md/jsdoc-to-markdown/tree/master/example/tags/summary)
