### ISSUE TITLE
Additional helpers not loaded @next

### ISSUE THREAD

**Issue by vdininski** [jsdoc2md/dmd#18]
At the moment I am unable to register additional helpers. I believe the problem lies here:
https://github.com/jsdoc2md/dmd/blob/next/lib/dmd.js#L113

After debugging it seems that `registerHelper` receives only the helper definition as the first argument, but no name.

**Comment by 75lb** [comment]
to register additional helpers, create a module which exposes the helpers like this one: https://github.com/jsdoc2md/dmd/blob/next/helpers/helpers.js

then pass the name of that file to dmd, like 
```
$ dmd --helper my-helpers.js
```

or 
```js
dmd({ helper: "my-helpers.js" });
```

if you look at the docs for "Handlebars.registerHelper" [here](http://handlebarsjs.com/reference.html), you'll see i'm using the "register multiple helpers at once" method.. 

any more queries, let me know..

**Comment by vdininski** [comment]
After more debugging I found the root cause - backwards incompatible helpers:

My previous module definition was:

```js
module.exports = function(handlebars) {
   handlebars.registerHelper(...);
}
```

but now it should be:

```js
module.exports.helperName = function(helperArg1, helperArg2,...) {
   // actual helper definition - no need to call handlebars.registerHelper
}
```

**Comment by 75lb** [comment]
Ah yes, that's true - the helper api changed a month or two ago.. glad you
found the issue..
