### ISSUE TITLE
How to output class field members separately from function members?

### ISSUE THREAD

**Issue by waynebloss** [jsdoc2md/dmd#24]
I am trying out jsdoc-to-markdown and I have an `hbs` template that contains this:

``` md
{{#class name="MyClassName"~}}
{{>member-index~}}
{{>separator~}}
{{>members~}}
{{/class}}
```

It works pretty well, except that all field and function members are listed in one big list. I was looking for something like a `field-index` and a `method-index`.

I don't see any documentation on what kind of partials are available to use. I actually changed `{{#module ...}}` to `{{#class}}` on a guess. Here's a better picture of what I think I'm looking for:

``` md
{{#class name="MyClassName"~}}
{{>field-index~}}
{{>method-index~}}
{{>separator~}}
{{>fields~}}
{{>methods~}}
{{/class}}
```

Is there anything like that?

**Comment by 75lb** [comment]
hi, it is possible using lower level helpers.. i will write up some examples when i get time..

**Comment by OpherV** [comment]
I'm also interested in this. I've been digging in DMD for the past day and it's really nontrivial

**Comment by 75lb** [comment]
There's some documentation on the `{{#class}}`, `{{#classes}}` etc helpers in the wiki: https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Cherry-picking-which-documentation-appears-in-output
