### ISSUE TITLE
Add note on how to migrate to V2

### ISSUE THREAD

**Issue by vvo** [jsdoc2md/dmd#34]
Hello! Nice move to sync API. I had to dig a bit to understand we had to move from:

```js
    let dmdStream = dmd({
      template: ...,
      helper: ['./scripts/helpers']
    });

    dmdStream.pipe(fs.createWriteStream('file.md')));
    dmdStream.end(JSON.stringify(data));
```

to:

```js
    const fileContent = dmd(data, {
      template: ...,
      helper: ['./scripts/helpers']
    });

    const filePath = 'file.md';
    fs.writeFile(filePath, fileContent);
```

Maybe worth adding to the readme. As a general rule, we try to have CHANGELOG.md, nice and simple.

**Comment by 75lb** [comment]
good morning! Yes, i will put some release notes on the repo, thanks!

**Comment by 75lb** [comment]
[done](https://github.com/jsdoc2md/dmd/releases/tag/v2.0.3), thanks.

**Comment by vvo** [comment]
Thx, is the https://github.com/jsdoc2md/dmd#synopsis still relevant?
