### ISSUE TITLE
Upgrade Handlebars package

### ISSUE THREAD

**Issue by maxkoryukov** [jsdoc2md/dmd#37]
Hello!

Looks, like the HBS 3.0.1 is vulnerable ( https://snyk.io/vuln/npm:handlebars:20151207 )

Lets upgrade to Handlebars 4? I could help with this

**Comment by 75lb** [comment]
duplicate of https://github.com/jsdoc2md/dmd/pull/35.

Thanks for offering to help!

**Comment by 75lb** [comment]
handlebars upgraded in the latest release of dmd (v3.0.7).
