### ISSUE TITLE
Is there a way to suppress a specific tag without editing the partial?

### ISSUE THREAD

**Issue by Redsandro** [jsdoc2md/dmd#40]
Say I want to slim down documentation and remove e.g. author and copyright because they are 500 times the same. Can I specify somewhere to ignore them, rather than copy and edit the partials?

Using `jsdoc-to-markdown`.

**Comment by 75lb** [comment]
Well, one way is to tweak the partial:  

1. Duplicate [this partial](https://github.com/jsdoc2md/dmd/blob/master/partials/all-docs/docs/body/body.hbs) into your project (important - it must have the same filename `body.hbs`). 
2. Remove the `{{>authors~}}` and `{{>copyright~}}` lines
3. run `jsdoc2md --partial tweaks/body.hbs`

The other way is to run [.getTemplateData()](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md#jsdoc2mdgettemplatedataoptions--promise) to get the template data, manually strip out the unwanted fields, then pass the data (as `options.data`) into [.render()](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md#jsdoc2mdrenderoptions--promise).

**Comment by Redsandro** [comment]
Thank you! :+1:
