### ISSUE TITLE
whitespace at the end of a line

### ISSUE THREAD

**Issue by staxmanade** [jsdoc2md/dmd#41]
I started playing with jsdoc-to-markdown to automate generating some API docs for https://github.com/approvals/Approvals.NodeJS.

I noticed that the api docs generated some output with extra whitespace at the end of some lines.

My challenge with this is if I open my editor (where I have `"trimTrailingWhitespace": true`) any readme mods I make will trim this trailing whitespace.

Then my "test" that verifies that the readme docs are the same as what's generated from the tool are equivalent will always make me copy back the whitespace.

I cloned this repo and started to take a look - but it's hard to tell what files have whitespace at the end on purpose vs what is not necessary.

Any thoughts?

For now, I'm going to write some code to trim trailing whitepsace before writing the docs out as a bandaid - but wanted to see if this would be worth adjusting at the source?

**Comment by 75lb** [comment]
Hi! the whitespace at the end of particular lines is significant, it is valid [Markdown syntax](https://daringfireball.net/projects/markdown/syntax#p).

> When you do want to insert a <br /> break tag using Markdown, you end a line with two or more spaces, then type return.
