### ISSUE TITLE
Update handlebars to address three security vulnerabilities

### ISSUE THREAD

**Issue by gregswindle** [jsdoc2md/dmd#44]
## Issue summary

I use `jsdoc-to-markdown` (i.e., the `jsdoc2md` CLI) to create API docs I can save in my repositories' GitHub wikis. It's a great tool: thanks!

I use several quality gates in my projects, including dependency checkers. Unfortunately, `jsdoc-to-markdown` has some nested dependencies that are out-of-date. In order to keep my projects' dependencies current, I've been shrink-wrapping them and updating the nested dependencies.  Just as I was about to write a script to update my `npm-shrinkwrap.json` files, I thought, "Why don't I just report the issue, [provide a (potential) fix](https://github.com/gregswindle/dmd), and submit a pull request?" :bowtie:

## Expected Behavior

The [`handlebars`]() package should be updated to version >=4.0.0 in order to address these vulnerabilities:

1. [Quoteless Attributes in Templates can lead to Content Injection](https://nodesecurity.io/advisories/handlebars_quoteless-attributes-in-templates-can-lead-to-xss) 
Discovered in a nested dependency: ` jsdoc-to-markdown@3.0.0 --> dmd@3.0.3 --> handlebars@3.0.3`
2. [Incorrect Handling of Non-Boolean Comparisons During Minification](https://snyk.io/vuln/npm:uglify-js:20150824)
Discovered in a nested dependency: `jsdoc-to-markdown@3.0.0 --> dmd@3.0.3 --> handlebars@3.0.3 --> uglify-js@2.3.6`
3. [Regular Expression Denial of Service](https://snyk.io/vuln/npm:uglify-js:20151024)
Discovered in a nested dependency: `jsdoc-to-markdown@3.0.0 --> dmd@3.0.3 --> handlebars@3.0.3 --> uglify-js@2.3.6`

## Current Behavior

The current version of `dmd@3.0.3` -- and, consequently, `jsdoc-to-markdown@3.0.0` -- uses a lower version of `handlebars`, which exposes the vulnerabilities described above.

## Possible Solution

Update `dmd` to use `handlebars@4.0.6`, which itself has updated its nested dependencies, thereby addressing the vulnerabilities:

```
$ npm install --save handlebars@latest
```

> ### :information_source: I have a pull request ready, if you wanna see it 
> I have [forked `jsdoc2md/dmd` with the following updates](https://github.com/gregswindle/dmd/tree/fix/update-vulnerable-dependencies). `npm test` passes locally as well as on [Travis-CI](https://travis-ci.org/gregswindle/dmd). I'd be happy to submit a pull request.
> 
> * Here's the badge that points to my fork: [![dependencies Status](https://david-dm.org/gregswindle/dmd/status.svg)](https://david-dm.org/gregswindle/dmd)
> * Here's a [sample API doc I created with the forked `dmd` using `handlebars@4.0.6`](https://github.com/gregswindle/dmd/wiki/Example-API-generated-by-jsdoc-to-markdown-with-forked-gregswindle-dmd).
>

## Vulnerability Reports

1. [See the Bithound security advisory](https://www.bithound.io/github/gregswindle/eslint-plugin-crc/develop/dependencies/npm/jsdoc-to-markdown#security-advisories) for one of my personal repositories.
2. [See the David dependency security warning](https://david-dm.org/jsdoc2md/dmd) for [`jsdoc2md/dmd`](https://github.com/jsdoc2md/dmd).

**Comment by 75lb** [comment]
hi, thanks for the great issue report! 

jsdoc2md is a command-line tool, not a server exposed to the public. The only person with access to the running process is you, therefore jsdoc2md only exposes vulnerabilities if you are trying to hack yourself.

Duplicate of https://github.com/jsdoc2md/dmd/pull/35.

**Comment by gregswindle** [comment]
Thanks @75lb. Not to be a stickler, but when `jsdoc2md` is executed on a corporate CI/CD pipeline/workflow, it is technically executed on a server. I agree that the attack surface might be small, but it exists nevertheless, and it's trivial to patch.

So I take it you **do not** want me to send a pull request, correct?

Either way, thanks for taking the time to reply.

**Comment by 75lb** [comment]
The attack surface is not small, it is non-existent. Even if your CI server was comprised by a hacker and they somehow got access to the running jsdoc2md process and exposed a vulnerability in handlebars, what could they do? Hijack your API docs?  Security is not an issue. 

If your PR updates the deps while not breaking the jsdoc2md output in any way, yes please raise it :)

**Comment by gregswindle** [comment]
I see your point: in fact, NSP doesn't seem to do nested package analysis (although I'm not sure why).

Regardless, the package upgrades don't break any of my tests, and I crave that green badge, so I'll send the PR. 💄 :on: 🐷 

I'll dig for you JSDoc annotated source and provide more test results with the PR, as well. Thanks!

**Comment by 75lb** [comment]
i think i will remove the David badge on dmd, the security alert is not
relevant/applicable and just gets people worried.

**Comment by 75lb** [comment]
handlebars upgraded in the latest release of dmd (v3.0.7).
