### ISSUE TITLE
Support Gitiles markdown rendering

### ISSUE THREAD

**Issue by Krinkle** [jsdoc2md/dmd#60]
Thanks for making [jsdoc-to-markdown](https://github.com/jsdoc2md/jsdoc-to-markdown). I love this library and it's amazing.

At Wikimedia Foundation, we host most source code repositories with Gerrit; using Gitiles as repository viewer (from Google; used for android, chromium, etc.; [googlesource.com example](https://chromium.googlesource.com/external/v8/), [wikimedia.org example](https://gerrit.wikimedia.org/g/performance/navtiming)).

Unfortunately, Gitiles does not support the `<dl>` HTML extension to markdown. The result is that [API.md (source)](https://gerrit.wikimedia.org/r/#/c/performance/fresnel/+/459409/21/API.md,unified) renders as [API.md (gitiles)](https://gerrit.wikimedia.org/g/performance/fresnel/+/f45643b919cb6e45442c3169e94367f55b212fe5/API.md) with much of the content missing:

| Okay (md-fileserver) | Broken (Gitiles)
|--|--
| ![rendered by md-fileserver](https://user-images.githubusercontent.com/156867/50120063-4a5eaf00-024c-11e9-94f7-9d4ea6e0ad55.png) |  ![rendered by Gitiles](https://user-images.githubusercontent.com/156867/50120099-606c6f80-024c-11e9-9496-cd96be8b9722.png)

I'm looking to bypass this problem with a set of custom partials, but I'm not sure where to begin and how much I'd have to override. Perhaps this could be part of jsdoc2md, e.g. via a preset of some kind. Would you accept a pull request to that end?

The resulting visual rendering might be less pleasing than the indentation of dictionary lists (which I quite like actually), but it would allow for wider compatibility.

(Upstream bug report: https://github.com/google/gitiles/issues/81)

**Comment by 75lb** [comment]
Hi mate, sorry for the slow reply. You should be able achieve the output you need by passing in your own [custom partials](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Create-a-custom-partial) or [plugin](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Create-a-plugin).

Start by overriding [the module-index partial](https://github.com/jsdoc2md/dmd/blob/master/partials/main-index/module-index/module-index.hbs) adding your own command-line arg value, e.g. 

```hbs
{{#if (optionEquals "module-index-format" "krinkle")}}{{>module-index-krinkle ~}}{{/if~}}
```

Next, you'll need to create the partial file `module-index-krinkle.hbs` (which contains your desired index template) and pass it in with your jsdoc2md command, e.g.

```
$ jsdoc2md --module-index-format krinkle --partial module-index.hbs module-index-krinkle.hbs --files lib/*
```

For example, if using the example partials and source files [here](https://gist.github.com/75lb/b4e781ea8d3461c71b35b78a2ff417c6), the above command would output: 


```
{ id: 'module:something',
  longname: 'module:something',
  name: 'something',
  kind: 'module',
  thisvalue: undefined,
  meta:
   { lineno: 1,
     filename: 'modulea.js',
     path: '/Users/llobrook/Documents/75lb/tmp/jdsoc2md/lib' },
  order: 0 }
{ id: 'module:anotherthing',
  longname: 'module:anotherthing',
  name: 'anotherthing',
  kind: 'module',
  thisvalue: undefined,
  meta:
   { lineno: 1,
     filename: 'moduleb.js',
     path: '/Users/llobrook/Documents/75lb/tmp/jdsoc2md/lib' },
  order: 1 }
CUSTOM MODULE LIST



MODULE: something
SIG-LINK:
[something](#module_something)


MODULE: anotherthing
SIG-LINK:
[anotherthing](#module_anotherthing)

CUSTOM MODULE LIST END
<a name="module_something"></a>

## something
<a name="module_anotherthing"></a>

## anotherthing
```

If you have any questions, you can message me using the Gitter room linked on the jsdoc2md README.

**Comment by 75lb** [comment]
[dmd-bitbucket](https://github.com/jsdoc2md/dmd-bitbucket) is an example of a dmd plugin enabling support for a different markdown renderer (which i think is what you require).

**Comment by 75lb** [comment]
closing, let me know if you have any more questions.
