### ISSUE TITLE
@typicalname separation for any parent

### ISSUE THREAD

**Issue by klaslundberg** [jsdoc2md/dmd#66]
When using typicalName in a class, the typical name gets applied to the instance, and the name gets applied which is beautiful. However, I wonder why this type of is limited to parents of class kind? There are many other scenarios where this would be applied nicely exactly the same way.

Simplified example of how I want jsdoc2md to work 
```js
/**
 * @exports myFunction
 * @typicalname otherFunction
 */
var myFunction = function() {
    /**
     * Documented as otherFunction.instanceMember
     * @member instanceMember
     * @memberof myFunction
     */
    this.instanceMember = 1;
};

/**
 * Should be documented as myFunction.defaultValue
 * @name defaultValue
 * @memberof myFunction
 */
myFunction.defaultValue = 2;

// then using the function somewhere else without having it as a class nor using `new`
var otherFunction = function() {};
myFunction.apply(otherFunction)
```

So, there would be scenarios for most parents to have the instance typical name separation. My suggestion is to remove the limit to the class parents. Otherwise another tag `@instanceName` could be added that works for all parents. It could also be extended with `@staticName` & `@innerName`.

For now, I just forked and removed the class parent check, which works perfectly for all my cases. I could make a PR if you like.

**Comment by 75lb** [comment]
Yes, submit a PR please - I'll take a look..

**Comment by klaslundberg** [comment]
I think this was due to something else which will remain unknown. It seems to work fine as intended now with my current configuration and documentation. Keep calm and carry on.

**Comment by klaslundberg** [comment]
I did some further research and found out that it was actually still a valid issue when having anything that is not a class but can make use of instance members, such as a function or mixin.

**Comment by 75lb** [comment]
Sorry, closing. Merging this would enable the feature for all users and I'm not convinced there's a strong enough use case, that it's a feature all users need.
