### ISSUE TITLE
Some jsdoc properties not being returned from the params function.

### ISSUE THREAD

**Issue by tmonck** [jsdoc2md/dmd#67]
I am curious if it was intentional to not return some of the properties to the templates from the params function. I am personally wanting to use the optional property. It's a relatively small fix to add that one property and I could provide a PR, but while I was looking I was curious if there was a specific reason you didn't include all the possible jsdoc properties during formatting. I think that if all the properties were returned then it would make the templating much more flexible.

**Comment by 75lb** [comment]
Hi, could you post a link to the params function you are referring to please?

**Comment by tmonck** [comment]
I apologize for my delay in responding https://github.com/jsdoc2md/dmd/blob/master/helpers/helpers.js#L284-L302. Currently this function is not returning of the param is optional or not.

**Comment by 75lb** [comment]
> I am curious if it was intentional to not return some of the properties to the templates from the params function.

Hmm, this code is several years old - i can't remember whether it was intentional or not. 

If you need this function to return `optional` then make the change and send me the PR. I will test it, if the change does not break anything else then I'll merge it.

**Comment by tmonck** [comment]
I submitted the PR was curious if you had the opportunity to test it out.

**Comment by 75lb** [comment]
merged and released in dmd v5.0.0, thanks

**Comment by 75lb** [comment]
also released in dmd v4.0.6 so users of the current version of jsdoc2md will pick up the change.
