### ISSUE TITLE
Add support for `{@linkcode}`, `{linkplain}` tags and  clever links, monospace links options

### ISSUE THREAD

**Issue by zanerock** [jsdoc2md/dmd#85]
The standard jsdoc spec defnies support for monospace and plain text link formatting which is currently missing from jsdoc-to-markdown. (See [jsdoc `{@link}` page](https://jsdoc.app/tags-inline-link).)

To match the jsdoc links, let's add `{@linkcode}` (which are rendered in monospace) and `{@linkplain}` (which are rendered in plain text) tags as well as 'clever links' and 'monospace links' options. When 'clever links' is true, then links are rendered in monospace unless the link target is a URL (e.g., links to functions, modules, classes, etc. are rendered in monospace). When 'monospace links' is true, then `{@link}` tags are rendered in monospace. The 'monospace links' options is ignored if 'clever links' is true.

Support for setting the options from the command line is proposed in [jsdoc-to-markdown#301](https://github.com/jsdoc2md/jsdoc-to-markdown/issues/301).

**Comment by 75lb** [comment]
Merged, see https://github.com/jsdoc2md/jsdoc-to-markdown/issues/301
