### ISSUE TITLE
Respect line endings

### ISSUE THREAD

**Issue by jaxer** [jsdoc2md/dmd#92]
Generated doc can end up with mixed encodings on windows.
Seems like templates (in jsdoc2md packages) are using LF encoding (as they are installed by npm and not converted by git) and windows sources (by default converted by git) use CRLF.

A bigger problem though is unnecessary diffs generated in cross-platform projects. I.e. if doc generated on Mac and later regenerated on Windows then mixed line endings would result in unnecessary diffs.

**Comment by 75lb** [comment]
Hi, I've implemented an `--EOL` option - specify either `win32` or `posix`.. For example `jsdoc2md --EOL win32 index.js` will force the output to use `\r\n` line-endings throughout. 

If you have a moment, feel free to test the prerelease and let me know your thoughts. 

```
npm install -g jsdoc-to-markdown@next
```

**Comment by 75lb** [comment]
Closing - this feature will be in the next release, watch this space. Let me know if there's anything else.
