### ISSUE TITLE
Multiline not working on some markdown sites

### ISSUE THREAD

**Issue by BHare1985** [jsdoc2md/dmd#93]
On NPM the multiline examples aren't working:

https://www.npmjs.com/package/binaryquadkey

Not sure if github is your only md target or not.

**Comment by 75lb** [comment]
Hi, I've implemented an `--EOL` option - specify either `win32` or `posix`.. For example `jsdoc2md --EOL win32 index.js` will force the output to use `\r\n` line-endings throughout. 

If you have a moment, feel free to test the prerelease and let me know your thoughts. 

```
npm install -g jsdoc-to-markdown@next
```

**Comment by 75lb** [comment]
Closing - this feature will be in the next release, watch this space. Let me know if there's anything else.
