### ISSUE TITLE
@hideconstructor does not hide constructor

### ISSUE THREAD

**Issue by ozum** [jsdoc2md/dmd#94]
Hi,

I'm using `@hideconstructor` to hide constructor from markdown documents. I even coupled it with `@private`, but constructor is always documented.

Example (I tried every combination of `@private` and `@hideconstructor`)

```js
/**
 * Some details
 * @public
 * @hideconstructor
 */
class MyClass {
  /**
   * Constructor details
   * @private
   * @hideconstructor
   */
  constructor() {
    this.attr = 1;
  }
}
```

Kind Regards,

**Comment by 75lb** [comment]
Implemented and available in the [jsdoc2md v9 pre-release](https://github.com/jsdoc2md/jsdoc-to-markdown/releases/tag/v9.0.0-5) which you can install and test, if you like. 

There's an example of the output [in the testbed.](https://github.com/jsdoc2md/testbed/tree/master/build/jsdoc/global/hideconstructor)
